import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="font-sans bg-gray-50">
				<nav className="p-4 bg-white shadow-md">
					<Link href="/" className="text-xl font-bold">
						EDGAR API
					</Link>
				</nav>
				<main>{children}</main>
			</body>
		</html>
	);
}
